// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkuxndwjjhjegjmnktrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdXhuZHdqamhqZWdqbW5rdHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODMzODMsImV4cCI6MjA2Njc1OTM4M30.vYa9WuU0MHkAKF0KKCGRARBWZNchRgct4Q0ZvOcX8uM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);